# Generated by Django 2.1.7 on 2020-03-07 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QQUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_times', models.DateTimeField(auto_now_add=True)),
                ('update_times', models.DateTimeField(auto_now=True)),
                ('openid', models.CharField(max_length=64, verbose_name='openid')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'QQ绑定用户',
                'verbose_name_plural': 'QQ绑定用户',
                'db_table': 'tb_qq',
            },
        ),
    ]
